apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-target-eu
  labels:
    app: multi-target-eu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-target-eu
  template:
    metadata:
      labels:
        app: multi-target-eu
    spec:
      containers:
      - name: helloworld
        image: ghcr.io/pipe-cd/helloworld:v0.37.0
        args:
          - server
        ports:
        - containerPort: 9085
