apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  name: canary-rollout-with-service
  labels:
    env: test
  description: Test canary rollout with service creation
  pipeline:
    stages:
      - name: K8S_CANARY_ROLLOUT
        with:
          replicas: 50%
          createService: true
  plugins:
    kubernetes_multicluster:
      input:
        manifests:
          - deployment.yaml
          - service.yaml
        kubectlVersion: 1.32.2
      service:
        name: simple
