apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  name: baseline-clean-test
  labels:
    env: test
  description: Test full canary + baseline + clean pipeline
  pipeline:
    stages:
      - name: K8S_CANARY_ROLLOUT
        with:
          replicas: 1
      - name: K8S_BASELINE_ROLLOUT
        with:
          replicas: 1
      - name: K8S_CANARY_CLEAN
      - name: K8S_BASELINE_CLEAN
  plugins:
    kubernetes_multicluster:
      input:
        manifests:
          - deployment.yaml
        kubectlVersion: 1.32.2
